import type { Metadata } from "next";
import { Cairo } from "next/font/google";

import "./normalize.css";
import "./globals.css";

import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import ScrollToTopBtn from "@/components/ScrollToTopBtn";

const cairo = Cairo({
  subsets: ["latin"],
  variable: "--font-cairo",
});

export const metadata: Metadata = {
  title: "Elzero Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className}`}>
        <Header />
        <main>{children}</main>
        <Footer />
        <ScrollToTopBtn />
      </body>
    </html>
  );
}
